In [48]:
import pandas as pd


import pandas as pd
import sqlite3

# https://www.kaggle.com/datasets/wyattowalsh/basketball
con = sqlite3.connect("data/basketball.sqlite")


df = pd.read_sql_query("""
SELECT *
FROM Player_Salary t1 
JOIN Player t2 
ON t1.namePlayer = t2.full_name 
JOIN Player_Attributes t3 
ON t2.first_name = t3.FIRST_NAME and t2.last_name = t3.LAST_NAME
""", con)

In [49]:
df = df.fillna(0)
df.columns

Index(['slugSeason', 'nameTeam', 'namePlayer', 'statusPlayer', 'isFinalSeason',
       'isWaived', 'isOnRoster', 'isNonGuaranteed', 'isTeamOption',
       'isPlayerOption', 'typeContractDetail', 'value', 'id', 'full_name',
       'first_name', 'last_name', 'is_active', 'ID', 'FIRST_NAME', 'LAST_NAME',
       'DISPLAY_FIRST_LAST', 'DISPLAY_LAST_COMMA_FIRST', 'DISPLAY_FI_LAST',
       'PLAYER_SLUG', 'BIRTHDATE', 'SCHOOL', 'COUNTRY', 'LAST_AFFILIATION',
       'HEIGHT', 'WEIGHT', 'SEASON_EXP', 'JERSEY', 'POSITION', 'ROSTERSTATUS',
       'GAMES_PLAYED_CURRENT_SEASON_FLAG', 'TEAM_ID', 'TEAM_NAME',
       'TEAM_ABBREVIATION', 'TEAM_CODE', 'TEAM_CITY', 'PLAYERCODE',
       'FROM_YEAR', 'TO_YEAR', 'DLEAGUE_FLAG', 'NBA_FLAG', 'GAMES_PLAYED_FLAG',
       'DRAFT_YEAR', 'DRAFT_ROUND', 'DRAFT_NUMBER', 'PTS', 'AST', 'REB',
       'ALL_STAR_APPEARANCES', 'PIE'],
      dtype='object')

In [57]:
df['TEAM'] = df.TEAM_CITY + ' ' + df.TEAM_NAME

In [58]:
df[['slugSeason', 'namePlayer', 'TEAM', 'DRAFT_NUMBER', 'ALL_STAR_APPEARANCES', 'PTS', 'AST', 'REB']]

,slugSeason,namePlayer,TEAM,DRAFT_NUMBER,ALL_STAR_APPEARANCES,PTS,AST,REB
0,2020-21,Bogdan Bogdanovic,Atlanta Hawks,27,0.0,9.6,2.3,3.3
1,2021-22,Bogdan Bogdanovic,Atlanta Hawks,27,0.0,9.6,2.3,3.3
2,2022-23,Bogdan Bogdanovic,Atlanta Hawks,27,0.0,9.6,2.3,3.3
3,2023-24,Bogdan Bogdanovic,Atlanta Hawks,27,0.0,9.6,2.3,3.3
4,2020-21,Brandon Goodwin,Atlanta Hawks,Undrafted,0.0,3.9,1.6,1.0
...,...,...,...,...,...,...,...,...
949,2020-21,Russell Westbrook,Washington Wizards,4,0.0,21.7,10.3,9.5
950,2021-22,Russell Westbrook,Washington Wizards,4,0.0,21.7,10.3,9.5
951,2022-23,Russell Westbrook,Washington Wizards,4,0.0,21.7,10.3,9.5
952,2020-21,Thomas Bryant,Washington Wizards,42,0.0,14.3,1.5,6.1
953,2021-22,Thomas Bryant,Washington Wizards,42,0.0,14.3,1.5,6.1